<?php

namespace backend\modules\paper\models;

use Yii;

/**
 * This is the model class for table "tbl_pap_page_template".
 *
 * @property integer $id
 * @property string $name
 * @property integer $no_of_pages
 * @property string $created_at
 * @property integer $created_by
 * @property string $status_id
 */
class TblPapMagzineTemplate extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_pap_magzine_template';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['no_of_pages', 'created_by'], 'integer'],
            [['created_at'], 'safe'],
            [['name'], 'string', 'max' => 50],
            [['status_id'], 'string', 'max' => 1],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'no_of_pages' => 'No Of Pages',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'status_id' => 'Status ID',
        ];
    }

    public function beforeSave($insert)
    {
        $this->created_at = date('Y-m-d H:i:s');
        $this->created_by = 1;
        $this->status_id = 1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }    
}
